"""added time to recipe, and pass and email to user

Revision ID: 0e717a7759d7
Revises: 880b5e719fa5
Create Date: 2020-05-28 13:59:54.144757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e717a7759d7'
down_revision = '880b5e719fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_recipe_created_time'), 'recipe', ['created_time'], unique=False)
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    op.drop_index(op.f('ix_recipe_created_time'), table_name='recipe')
    op.drop_column('recipe', 'created_time')
    # ### end Alembic commands ###
