"""about me and last seen added to user

Revision ID: 3928db9ee944
Revises: 0e717a7759d7
Create Date: 2020-06-01 14:09:14.115422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3928db9ee944'
down_revision = '0e717a7759d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
